# Generated by Django 3.0.5 on 2020-04-27 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, verbose_name='City')),
                ('city_psc', models.IntegerField(max_length=5, verbose_name='City psc')),
            ],
            options={
                'ordering': ['city_name', 'city_psc'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, verbose_name='Class name')),
            ],
            options={
                'ordering': ['field', 'class_name'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, unique=True, verbose_name='Field name')),
                ('field_short', models.CharField(max_length=5, unique=True, verbose_name='Field short name')),
            ],
            options={
                'ordering': ['field_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, unique=True, verbose_name='Subject name')),
                ('subject_short', models.CharField(max_length=3, unique=True, verbose_name='Subject short name')),
            ],
            options={
                'ordering': ['subject_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_short', models.CharField(max_length=5, unique=True, verbose_name='Teacher abbrev')),
                ('teacher_name', models.CharField(max_length=30, verbose_name='Teacher name')),
                ('teacher_surname', models.CharField(max_length=50, verbose_name='Teacher surname')),
                ('teacher_pid', models.CharField(max_length=11, unique=True, verbose_name='Teacher pid (rodne cislo)')),
                ('teacher_subjects', models.ManyToManyField(help_text="Select teacher's subjects", to='zakovska.Subject')),
            ],
            options={
                'ordering': ['teacher_short'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_pid', models.CharField(max_length=11, verbose_name='Student PID (rodne cislo)')),
                ('student_name', models.CharField(max_length=30, verbose_name='Student name')),
                ('student_surname', models.CharField(max_length=50, verbose_name='Student surname')),
                ('student_street', models.CharField(max_length=50, verbose_name='Street')),
                ('student_house_number', models.IntegerField(max_length=5, verbose_name='House number')),
                ('student_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakovska.Address')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakovska.Class')),
            ],
            options={
                'ordering': ['student_surname', 'student_name'],
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50, verbose_name='Topic')),
                ('mark', models.DecimalField(choices=[(1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], decimal_places=1, help_text='Select mark', max_digits=2, verbose_name='Mark')),
                ('mark_weight', models.DecimalField(choices=[(0.1, '10%'), (0.2, '20%'), (0.3, '30%'), (0.4, '40%'), (0.5, '50%'), (0.6, '60%'), (0.7, '70%'), (0.8, '80%'), (0.9, '90%'), (1.0, '100%')], decimal_places=1, help_text='Select mark weight', max_digits=2, verbose_name='Mark weight')),
                ('date', models.DateField(auto_now=True, help_text='YYYY-MM-DD', verbose_name='Date')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='Comment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakovska.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakovska.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakovska.Teacher')),
            ],
            options={
                'ordering': ['-date', 'student'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakovska.Field'),
        ),
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(help_text='Select class subjects', to='zakovska.Subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakovska.Teacher'),
        ),
    ]
