# Generated by Django 3.0.5 on 2020-04-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakovska', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city_psc',
            field=models.IntegerField(verbose_name='City psc'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_house_number',
            field=models.IntegerField(verbose_name='House number'),
        ),
    ]
