# Generated by Django 3.0.5 on 2020-04-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakovska', '0007_auto_20200427_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark_weight',
            field=models.FloatField(choices=[(0.1, '10%'), (0.2, '20%'), (0.3, '30%'), (0.4, '40%'), (0.5, '50%'), (0.6, '60%'), (0.7, '70%'), (0.8, '80%'), (0.9, '90%'), (1.0, '100%')], help_text='Select mark weight', verbose_name='Mark weight'),
        ),
    ]
