# Generated by Django 3.0.5 on 2020-04-27 09:55

from django.db import migrations, models
import zakovska.models


class Migration(migrations.Migration):

    dependencies = [
        ('zakovska', '0008_auto_20200427_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to=zakovska.models.photo_path, verbose_name='Student photo'),
        ),
    ]
