# Generated by Django 3.0.5 on 2020-05-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakovska', '0011_auto_20200525_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachersubject',
            options={'ordering': ['teacher']},
        ),
    ]
