# Generated by Django 3.0.5 on 2020-06-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakovska', '0016_auto_20200613_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachersubject',
            options={'ordering': ['teacher']},
        ),
    ]
