# Generated by Django 3.0.5 on 2020-06-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakovska', '0017_auto_20200613_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark_weight',
            field=models.IntegerField(choices=[(10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], help_text='Select mark weight', verbose_name='Mark weight'),
        ),
    ]
