# Generated by Django 3.0.5 on 2020-06-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakovska', '0019_auto_20200613_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='YYYY-MM-DD', verbose_name='Date'),
        ),
    ]
